Feature/메인 와이어프레임
pawland-team/Pawland-FE pull request #29
Opened 2024-04-27 04:39 UTC by mingzzi96

## 🛠️주요 변경 사항

- 메인 작업
- 공용 컴포넌트(헤더/푸터) 레이아웃 작업
- 스토리북에 각종 컴포넌트 올라가있습니다.

## 📣리뷰어가 꼭 알아야 하는 사항

- 링크는 아직 페이지 경로를 모르겠어서 넣지 않았습니다. (팀 깃헙 제외)
- 푸터 sns 로고 작업이 완료되지 않아서 해당 부분은 제외하고 작업했습니다.
- 로그인 전/후 디자인은 스토리북에서 확인해주세요.
- 로그인 여부 체크하는 거는 로그인 쿠키 작업 완료되면 이어서 하겠습니다. (찜 눌렀을 때 / 헤더)
- 반려동물 행사 슬라이더는 오늘부터 api 작업하면서 진행하려고 합니다

## ❗관련이슈

- closed: #17 

## 🖼️스크린샷(선택)

<img width="444" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/134386378/1814d54a-a8b8-42d0-99c5-ca5ac47823eb">

제 맥북에서 사이즈가 너무 꽉찬 느낌이 드는데
다들 확인한번 해주시죠!

2024-04-27 11:31 UTC, DanteSnow approved these changes
고생 많으셨습니다 지민님!! 폴더구조는 일단 우선순위가 아니니까, 작업 다 끝나고 시간 남으면 같이 공부하면서 리팩토링해용!!👍👍

2024-04-27 12:49 UTC, Vegatality approved these changes

2024-04-27 12:49 UTC, Vegatality commented on src/shared/ui/buttons/common-button/common-button.tsx
> + */
이런 경우에는 타입스크립트 프로퍼티 하나하나 위에다가 적는 것이 더 일반적입니다.

예를 들어

```ts
interface CommonButtonProps {
  /**
   *  button 안에 들어갈 요소
   */
  children: ReactNode;
}
```

더 올바른 JSDoc 작성법을 보고 싶거나 더 다양한 Block tags(@)의 기능을 보고 싶으시면 
https://jsdoc.app/ 와 https://github.com/jsdoc/jsdoc를 참고해주세요.

2024-04-27 12:49 UTC, Vegatality commented on src/shared/ui/avatar-image/avatar-image.tsx
> +      <img src={imageSrc} alt={nickname ? `${nickname}님의 프로필 이미지` : '프로필 이미지'} />
Image 컴포넌트가 아닌 img 태그를 사용하셨군요. 특별한 이유가 있을까요?

2024-04-27 12:49 UTC, Vegatality commented on public/assets/images/product/test-image.png
저라면 product 보다는 mock 이라는 폴더에 넣고 이름을 좀 더 구체적으로 지었을 것 같습니다.
mock 이미지가 하나만은 아니니까요!

2024-04-27 13:49 UTC, jinyoung1018 approved these changes
지민님 수고많으셨습니당! 저도 작업하면서 아직 폴더구조가 어렵네용 같이 화이팅해용!!

2024-04-27 14:14 UTC, Vegatality requested changes

2024-04-27 14:14 UTC, Vegatality commented on src/app/styles/global.ts
아래와 같이 변경해서 lint가 올바르게 검사할 수 있게 만들어주세요.

```ts
import { createGlobalStyle, css } from 'styled-components';

import { pretendard } from './font/font';
import resetCss from './reset';

const GlobalStyle = createGlobalStyle`${css`
  ${resetCss}
  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    font-family: ${pretendard.style.fontFamily}, sans-serif;
    word-break: keep-all;
  }
  html,
  body {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    font-size: 62.5%; /* 1rem = 10px */
    input,
    textarea,
    select,
    button {
      background: transparent;
      border: 0;
    }
    button {
      cursor: pointer;
      padding: 0;
      border: none;
    }
    a {
      cursor: pointer;
      color: unset;
      text-decoration: none;
      &[role='button']:focus-visible {
        border: 1px solid #007bff;
      }
    }
    input,
    textarea {
      resize: none;
      outline: none;
    }
    ul {
      list-style-type: none;
    }
  }
`}
`;

export default GlobalStyle;
```ts

2024-04-27 14:15 UTC, mingzzi96 commented on src/app/styles/global.ts
헉 넵 수정해두겠습니닷!!

2024-04-27 14:20 UTC, mingzzi96 commented on src/shared/ui/avatar-image/avatar-image.tsx
> +      <img src={imageSrc} alt={nickname ? `${nickname}님의 프로필 이미지` : '프로필 이미지'} />
아 여기 placeholder이미지로 외부 이미지 링크 임시로 가져오고 있어서용!
다음에 로그인 연결 시킬 때 Image 컴포넌트 제대로 써서 고쳐두겠습니당

2024-04-27 14:21 UTC, mingzzi96 commented on public/assets/images/product/test-image.png
홀리 거기까진 생각 못했네요 ㅜㅜ수정하겠습니돗!

2024-04-27 14:36 UTC, mingzzi96 commented on src/shared/ui/buttons/common-button/common-button.tsx
> + */
<img width="157" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/134386378/ae74bc95-e169-4b06-aa9d-3c0f71d0f6f3">

일단 불필요한 타입 설명 지워서 올렸습니닷..!

2024-04-27 14:36 UTC, Vegatality requested changes
변경 부탁드린부분 변경부탁드려요.

2024-04-27 14:36 UTC, Vegatality commented on src/app/styles/global.css
> +}
global.css 파일을 제거하고 global.ts 파일로 완전히 대체해주세요.

`.sr-only`와 `.background-clip-text`는 유틸 css 함수로 빼는 게 좋아보이네요.
styled-components가 제공하는 css 함수로 분리해보세요.
위치는 shared/ui/styles/utils 라든가 적절한 이름으로 분리할 필요성이 보이네요.

2024-04-27 14:36 UTC, Vegatality commented on src/app/styles/global.css
> +}
z-index는 theme을 통해 어플리케이션 전체에서 일괄적으로 관리될 수 있도록 변경해주세요.

2024-04-27 14:36 UTC, Vegatality commented on pages/_app.tsx
> +      <GlobalStyle />
GlobalStyle을 이 곳에 위치시키면 themeProvider 안쪽에 위치하지 못하기 때문에 theme 객체에 접근하지 못하게 됩니다. 
ThemeProvider와 함께 사용할 때 GlobalStyle 컴포넌트의 적절한 위치를 고민해보세요.

2024-04-27 14:36 UTC, Vegatality commented on src/app/styles/global.ts
storybook에서 styled component Global style 세팅하는 방법을 검색하여 preview.ts 파일을 적절하게 변경해주세요.
현재 storybook이 돌아가지 않는 이유는 이것 때문입니다.

2024-04-27 14:50 UTC, mingzzi96 commented on src/app/styles/global.css
> +}
반영 완료 👍🏼 !!

2024-04-27 15:02 UTC, mingzzi96 commented on src/app/styles/global.css
> +}
헉 utils 폴더가 좋겠네요! 다른 css 함수로 만든 파일들도 옮겨두었습니다.

2024-04-27 15:03 UTC, mingzzi96 commented on src/app/styles/global.css
> +}
1778b79e8b0ae5f86f5229df7b55acbe3e2a13c7

2024-04-27 15:04 UTC, mingzzi96 commented on pages/_app.tsx
> +      <GlobalStyle />
d50d46104d70de1430f4b8e9def2a6f8c11c9cd8 변경해 보았습니돗!!

2024-04-27 15:10 UTC, mingzzi96 commented on src/app/styles/global.ts
3aa2915d34d1a46b08d90dec5cbc4470bad588c9 적용했습니돗!! 이젠,,, 빨간불 그만,,,, 통과,,, 돼라,,,, ^_ㅜ

2024-04-27 16:37 UTC, Vegatality commented on src/app/styles/global.ts
이렇게도 잘 동작하나보네요.
공식문서에는 [이렇게](https://storybook.js.org/recipes/styled-components#3-provide-your-themes) 되어 있더군요.

2024-04-27 16:46 UTC, Vegatality requested changes
찐찐막 요청

2024-04-27 16:46 UTC, Vegatality commented on src/app/styles/global.ts
> +    font-family: ${pretendard.style.fontFamily}, sans-serif;
Imcre 폰트도 따로 ts 파일로 분리한 후에 global.ts 파일로 import 하면 좋겠네요. 
근데 이미 font.ts 파일이 있으니 임시방편으로 global.ts 파일로 직접 import 해야겠어요.
그러면 global.css 파일도 더 이상 필요 없어지니 삭제하면 되겠죠?(찐막 요청임)

2024-04-27 17:40 UTC, mingzzi96 commented on src/app/styles/global.ts
> +    font-family: ${pretendard.style.fontFamily}, sans-serif;
345195d9400ca49aa611a1edbe0093cc00b9ea3e 스토리북에서도 아임크리 폰트 잘 나오는것 확인했습니동!!!

문제는,, next.js localfont로 적용하고있는 프리텐다드입니당,,,,
스토리북에서는 아래 이미지와 같이 적용되고 있는데
<img width="293" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/134386378/2e0bc8f4-422f-4635-9dc0-a8caf5f9ab83">

프리텐다드가 아닌 것 같아 네트워크 확인해보니,
<img width="453" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/134386378/2d2287e0-b0fa-4fe4-946d-2af6f1f22208">
폰트를 못가져오고 있네용 ,,,,,,,,,,

preview에서 app.tsx에 해주는 것 처럼 해줘봤는데 안되네용
<img width="352" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/134386378/0e8900c6-f175-45ce-a259-2b62a92c47d9">
해당 부분은 내일 더 찾아볼게용!

2024-04-27 17:43 UTC, mingzzi96 commented on src/app/styles/global.ts
오 저는 둘 다 해본건데, 적용이 잘 되더라구용! (๑˃̵ᴗ˂̵)

2024-04-28 10:07 UTC, mingzzi96 commented on src/app/styles/global.ts
> +    font-family: ${pretendard.style.fontFamily}, sans-serif;
<img width="192" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/134386378/66f81b13-de04-4cf3-83f0-4db5fa8e1434">

스토리북에도 pretendard 적용 완료!!

2024-04-28 10:31 UTC, Vegatality approved these changes
고생하셨어요 ㅎㅎ!!

2024-04-28 10:31 UTC, Vegatality commented on .storybook/main.ts
https://storybook.js.org/docs/api/main-config-static-dirs

` staticDirs: ['../public',]` 만으로는 못 찾나 보네요???? 
해당 디렉토리 전부 로드한다고 생각했는데 말이죠.

2024-04-28 10:36 UTC, mingzzi96 commented on .storybook/main.ts
그러게말이에요!! 저도 public 경로 설정 해줬는데 대체 왜 안되는건지 ,,
거의 스토리북이랑 절교 직전까지 갔었는데용

```ts
'../../../../public/fonts/pretendard/Pretendard-Bold.woff',
```

폰트 경로는 저렇게 불러오고 있는데

```ts
'/images/logo/***.svg'
```
이미지는 이렇게 불러오고 있다보니까 public이면 안되는거였어요!

별거 아닌 이유 찾는다고 작업이 좀 늦었네용ㅋㅋㅋㅋㅋㅋ 하
아무튼 찐 최종..

2024-04-28 10:37 UTC, merged