feat, design: 커뮤니티 페이지 기능 구현, 디자인 수정, 기타 작업
pawland-team/Pawland-FE pull request #83
Opened 2024-05-11 07:18 UTC by DanteSnow

## 🛠️주요 변경 사항

- 커뮤니티 페이지(리스트 페이지, 게시물 상세 페이지, 게시물 등록 페이지) 기능 구현
- 커뮤니티 페이지(리스트 페이지, 게시물 상세 페이지, 게시물 등록 페이지) 디자인 수정 반영
- 로그인 페이지 소셜로그인 백엔드 연동 및 환경 변수 세팅
- 회원가입 페이지 닉네임 중복확인 기능 구현

## 📣리뷰어가 꼭 알아야 하는 사항

- 커밋이 많이 쌓였고, main 머지 하신다고 하셔서 지금까지 한 작업 PR 올립니다. 아직 미완성입니다.
- 커뮤니티 리스트 페이지 페이지네이션, 기본 필터 (최신순, 인기순, 추천순)은 아직 백엔드가 안 나와서 미구현입니다. 되는대로 바로 반영해서 PR 올리겠습니다.
- 텍스트 에디터도 아직 미구현입니다. 위에 말씀드린 미구현 기능이랑 같이 PR 올리겠습니다.
- 폴더구조, 스토리북, 리액트 쿼리 등은 일단 급한 불 부터 다 끄고 차근차근 정리하겠습니다. 코드리뷰는 그 때 천천히 해주셔도 됩니닷.. 죄송합니다😭😭😭😭😭😭😭😭😭😭😭😭

## ❗관련이슈

- closed: #27 
- closed: #59 
- closed: #73 

## 🖼️스크린샷(선택)
<img width="620" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/150772344/a2d7b425-f21d-42aa-9b0c-4d21fe763ef3">
<img width="620" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/150772344/acc122fb-edc1-43e3-983a-3a3430230977">
<img width="620" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/150772344/5c390d4c-07e6-46d3-b128-9445aa67730b">

2024-05-11 18:33 UTC, Vegatality commented
#88 
@DanteSnow 이 커밋 머지되면 에러 사라질 것 같습니다.
머지되면 다시 pull 받아서 update후에 pr 시도해보셔요.

2024-05-11 19:46 UTC, Vegatality requested changes

2024-05-11 19:46 UTC, Vegatality commented on src/pages/community/post/post-page.tsx
> +      const s3BucketBaseUrl = 'https://midcon-bucket.s3.ap-northeast-2.amazonaws.com/';
버킷 base url을 env로 숨겨야 할 것 같습니다.
숨겨도 pr기록에 남으니 github에 pr 기록 삭제해달라고 요청할 수도 있습니다.

2024-05-11 19:46 UTC, Vegatality commented on src/pages/community/post/post-page.tsx
> +      });
모달을 열고나서 그냥 뒤로가기 버튼을 눌러서 해당 페이지를 빠져나올 경우 모달이 그대로 화면이 떠 있게 됩니다.
그 이유는 모달이 Context로 관리하는 전역에 존재하는 모달이기 때문입니다.
그렇기 때문에 페이지마다 unMount될 때 closeModalLIst를 통해 모달을 닫아주는 로직을 적어줘야 합니다.
useEffect의 클린업 함수에 적어주면 되겠네요.

이러한 이유 때문에 한 페이지에서 띄우려는 모달이 여러 개일 경우 모달 키도 휴먼 에러를 방지하게 위해 constants 변수로 빼는 것이 좋습니다.

2024-05-11 19:46 UTC, Vegatality commented on src/shared/ui/modal/post-modal/index 2.ts
index 2.ts 파일과 index.ts 파일의 차이점이 있나요?

2024-05-12 02:57 UTC, DanteSnow commented on src/shared/ui/modal/post-modal/index 2.ts
엇, 저도 왜 생겼는지 모르겠습니다. 삭제하겠습니다!!

2024-05-12 02:58 UTC, DanteSnow commented on src/pages/community/post/post-page.tsx
> +      });
피드백 감사드립니다! 반영하겠습니다! 🫡

2024-05-12 02:58 UTC, DanteSnow commented on src/pages/community/post/post-page.tsx
> +      const s3BucketBaseUrl = 'https://midcon-bucket.s3.ap-northeast-2.amazonaws.com/';
넵! 저도 한 번 알아보겠습니다! 감사합니다! 👍🏻

2024-05-12 02:59 UTC, DanteSnow commented on next.config.mjs
> +  },
넵 맞습니다! ㅎㅎ 작업 끝나면 바꿔놓겠습니다!

2024-05-12 03:42 UTC, jinyoung1018 approved these changes
치현님 수고많으셨습니당!! 형민님이 올리신 pr 머지되고 린트 에러만 해결되면 될 것 같습니당!

2024-05-12 05:40 UTC, mingzzi96 approved these changes
<img width="261" alt="image" src="https://github.com/pawland-team/Pawland-FE/assets/134386378/1cb7da44-07ee-4757-93cc-4e59988b625c">

수고하셨습니다!

2024-05-12 08:55 UTC, closed without merging